export const MV_SHED_REPAIRS = [
  "Brake cylinder repair/replacement",
  "Brake pipe and hose replacement",
  "Angle cock repair",
  "Distributor valve checking",
  "Brake rigging adjustment",
  "Brake block replacement",
  "Spring replacement",
  "Friction wedge replacement",
  "Side bearer adjustment",
  "Centre pivot repairs",
  "Bogie frame inspection",
  "Wheel profile checking",
  "Wheel defects inspection",
  "Axle box examination",
  "Bearing inspection and replacement",
  "CBC inspection",
  "Draft gear replacement",
  "Coupler lock and knuckle repairs",
  "Yoke and follower inspection",
  "Door repairs",
  "Welding of cracks",
  "Panel patching",
  "Floor plate repairs",
  "Water-tightness repairs",
  "Corrosion treatment",
  "Sole bar repairs",
  "Cross bar repairs",
  "Headstock repairs",
  "Centre sill crack repairs",
  "BPC checks",
  "Load and clearance checks",
  "Safety fittings inspection"
];

export const SICK_LINE_ROH_REPAIRS = [
  "Brake block replacement",
  "Brake hose pipe replacement",
  "Angle cock replacement",
  "Distributor valve replacement",
  "Brake cylinder defects rectification",
  "Coupler/CBC minor repairs",
  "Draft gear replacement",
  "Spring replacement",
  "Side bearer adjustment",
  "Wheel defects inspection",
  "Door repairs",
  "Minor welding and patching",
  "Leakages in air brake system",
  "Safety item replacement",
  "Brake power testing",
  "Complete bogie dismantling and inspection",
  "Spring testing and replacement",
  "Friction wedge examination",
  "Side bearer overhaul",
  "Centre pivot inspection",
  "CBC and draft gear overhaul",
  "Air brake equipment overhaul",
  "Brake cylinder overhaul",
  "Distributor valve testing",
  "Wheel set examination",
  "Bearing inspection",
  "Replacement of worn components",
  "Body repairs and corrosion treatment",
  "Painting/touch-up where required",
  "Checking all dimensions and clearances"
];
