const ExcelJS = require('exceljs');

class ExcelService {
  /**
   * Generates a formatted Excel workbook
   * @param {Object} data - Contains title, user, and multiple sheets data
   * @returns {Promise<Buffer>}
   */
  static async generateWorkbook(data) {
    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'Wagon Whisper';
    workbook.lastModifiedBy = data.user.name;
    workbook.created = new Date();
    workbook.modified = new Date();

    // 1. Summary Sheet
    const summarySheet = workbook.addWorksheet('Summary');
    this.createSummarySheet(summarySheet, data);

    // 2. Data Sheet
    const dataSheet = workbook.addWorksheet('Data');
    this.createDataSheet(dataSheet, data.headers, data.rows);

    return await workbook.xlsx.writeBuffer();
  }

  static createSummarySheet(sheet, data) {
    sheet.columns = [
      { header: 'Property', key: 'prop', width: 30 },
      { header: 'Value', key: 'val', width: 50 }
    ];

    // Style the header row
    sheet.getRow(1).font = { bold: true };
    sheet.getRow(1).fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFE0E0E0' }
    };

    sheet.addRow({ prop: 'Report Name', val: data.title });
    sheet.addRow({ prop: 'Generated By', val: data.user.name });
    sheet.addRow({ prop: 'Generated Date', val: new Date().toLocaleString() });
    sheet.addRow({ prop: 'Total Records', val: data.rows.length });
    
    if (data.filters) {
      sheet.addRow({ prop: 'Filters Applied', val: JSON.stringify(data.filters) });
    }
  }

  static createDataSheet(sheet, headers, rows) {
    // Setup Columns
    sheet.columns = headers.map(header => ({
      header: header,
      key: header.toLowerCase().replace(/[^a-z0-9]/g, '_'),
      width: Math.max(header.length + 5, 15) // Dynamic width
    }));

    // Style headers
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF4472C4' } // Professional Blue
    };
    headerRow.alignment = { vertical: 'middle', horizontal: 'center' };

    // Auto-filter
    sheet.autoFilter = {
      from: { row: 1, column: 1 },
      to: { row: 1, column: headers.length }
    };

    // Add Rows
    rows.forEach(rowData => {
      // Map array to object based on keys
      const rowObj = {};
      headers.forEach((header, i) => {
        const key = header.toLowerCase().replace(/[^a-z0-9]/g, '_');
        rowObj[key] = rowData[i];
      });
      sheet.addRow(rowObj);
    });

    // Alternate row banding (optional, but requested professional format)
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1 && rowNumber % 2 === 0) {
        row.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF2F2F2' }
        };
      }
    });
  }
}

module.exports = ExcelService;
