const PDFDocument = require('pdfkit');

class PDFService {
  /**
   * Generates a railway professional PDF
   * @param {Object} data - Contains title, user, and table data
   * @returns {Promise<Buffer>}
   */
  static async generateReport(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const buffers = [];

        doc.on('data', buffers.push.bind(buffers));
        doc.on('end', () => resolve(Buffer.concat(buffers)));

        // Header
        this.generateHeader(doc, data.title, data.user);
        
        // Body (Table)
        this.generateTable(doc, data.headers, data.rows);

        // Footer is generated per page during page add
        // Let's manually trigger footer for all pages at the end
        const pages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
        for (let i = 0; i < pages; i++) {
          doc.switchToPage(i);
          this.generateFooter(doc, i + 1, pages);
        }

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  static generateHeader(doc, title, user) {
    doc
      .fillColor('#444444')
      .fontSize(20)
      .text('Wagon Whisper', 50, 45, { align: 'right' })
      .fontSize(10)
      .text('Railway C&W Department', 50, 70, { align: 'right' })
      .text(`Generated by: ${user.name}`, 50, 85, { align: 'right' })
      .text(`Date: ${new Date().toLocaleDateString()}`, 50, 100, { align: 'right' });

    doc
      .fontSize(16)
      .fillColor('#000000')
      .text(title.toUpperCase(), 50, 130, { align: 'center' });

    doc.moveDown(2);
  }

  static generateFooter(doc, pageNumber, totalPages) {
    doc
      .fontSize(8)
      .fillColor('#888888')
      .text(
        `Generated by Wagon Whisper - Page ${pageNumber} of ${totalPages}`,
        50,
        doc.page.height - 50,
        { align: 'center', lineBreak: false }
      );
  }

  static generateTable(doc, headers, rows) {
    const startY = doc.y;
    const rowHeight = 20;
    const colWidth = (doc.page.width - 100) / headers.length; // distribute evenly
    
    // Draw Headers
    doc.font('Helvetica-Bold').fontSize(10).fillColor('#000000');
    headers.forEach((header, i) => {
      doc.text(header, 50 + i * colWidth, startY, { width: colWidth, align: 'left' });
    });
    
    this.drawLine(doc, startY + 15);

    // Draw Rows
    let currentY = startY + 25;
    doc.font('Helvetica').fontSize(9).fillColor('#333333');

    rows.forEach(row => {
      // Handle page breaks
      if (currentY > doc.page.height - 100) {
        doc.addPage();
        currentY = 50;
      }

      row.forEach((cell, i) => {
        const text = cell !== null && cell !== undefined ? String(cell) : '-';
        doc.text(text, 50 + i * colWidth, currentY, { width: colWidth, align: 'left' });
      });
      
      currentY += rowHeight;
      this.drawLine(doc, currentY - 5);
    });
  }

  static drawLine(doc, y) {
    doc.strokeColor('#cccccc').lineWidth(1).moveTo(50, y).lineTo(doc.page.width - 50, y).stroke();
  }
}

module.exports = PDFService;
